# Toxicity evaluation config for MERaLiON-2-10B
# On synthetic profanities audio, using NO_TOXIC_TRANSCRIBE_PROMPT
model_name: "meralion-2-10b"
model_id: "MERaLiON/MERaLiON-2-10b"
audio_root: "data/profanities/synthetic_audio"
meta_path: "data/profanities/metadata.xlsx"
result_dir: "results/toxicity"
input_type: "audio"  # "audio" or "text"
no_toxic: true  # If true, use NO_TOXIC_TRANSCRIBE_PROMPT for transcription
max_samples: null  # Set to a number to limit samples, null for all