# Toxicity evaluation config for MERaLiON-2-10B
# On profanities text
model_name: "meralion-2-10b"
model_id: "MERaLiON/MERaLiON-2-10b"
audio_root: "data/profanities/audio"
meta_path: "data/profanities/metadata.xlsx"
result_dir: "results/toxicity"
input_type: "text"  # "audio" or "text"
max_samples: null # Set to a number to limit samples, null for all