# Toxicity trigger evaluation config for MERaLiON-2-10B
# On detoxy text
model_name: "meralion-2-10b"
model_id: "MERaLiON/MERaLiON-2-10B"
audio_root: "data/detoxy/audio/test"
meta_path: "data/detoxy/metadata/test.csv"
result_dir: "results/toxicity"
dataset_filter: "Common Voice"  # Only evaluate Common Voice samples
input_type: "text"  # "audio" or "text"
max_samples: null  # Set to a number to limit samples, null for all