# Self-curated dataset robustness evaluation (test1-test2 with ground truth)
dataset_manifest: "data/manifests/self_curated.jsonl"
dataset_audio_dir: "data/robustness/audio"
text_field: "text"
results_dir: "results/self_curated"
seeds: [13, 17, 23]
models:
  - meralion-2-10b
  - meralion-2-3b
  - whisper-small

corruptions:
  none: [0]
  noise_snr_db: [30, 20, 10]
  speed: [0.9, 0.8, 1.1]
  pitch_semitones: [-2, 2, 4]
  reverb_decay: [0.2, 0.5, 0.8]
  clipping_ratio: [0.98, 0.9, 0.8]

bootstrap:
  n_samples: 1000
  alpha: 0.05
